### ISSUE TITLE
Release Checklist

### ISSUE THREAD

**Issue by marfvr** [valory-xyz/open-autonomy#166]
**Is your feature request related to a problem? Please describe.**

Complete the following tasks:

- [x] improving test coverage to spot bugs (especially after #161)
    - [x] improve test cases in order to cover also the lines mentioned here: https://github.com/valory-xyz/consensus-algorithms/pull/170#discussion_r735410818; addressed with #175 
- [x] double check new mechanism to spot flaws (especially after #161)
    - [x] consider duplication of rounds in state machine executions; i.e. self-loop transitions must be detected when taken, and so the check on the current round id is not enough to do so (addressed by #194)
- [X] revise documentation after new changes (especially after #161); addressed by #176
- [x] complete #84 (3b1f4d3)
- [X] check #126 is actually done (add a test) (addressed with #195)
- [x] `NO_MAJORITY` event is not implemented (#129)
- [X] replace `EXIT_A` and `EXIT_B` events into `EXIT` event (2426cf8)
- [x] fix inconsistencies in the FSM spec (addressed by #176):
    - [x] `NO_MAJORITY` from Observe round cannot be applied as each participant can submit a different observation
    - [x] Discuss `RETRY_TIMEOUT`: should it be implemented at the behaviour level? Or act as a time window in which all the obervations must be done and, when it expires, the already submitted observations are discarded?

**Describe the solution you'd like**
Address the above.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a
